Repository linw1995/nvim-mcp, pull requests merged in 2025-08, with the labels that each got.

#8 Update documentation to reflect 11 MCP tools and add symbol APIs
  .gitignore
  CLAUDE.md
  README.md
  docs/instructions.md
Labels: documentation

#15 Add universal text document identifier system for enhanced LSP operations
  CLAUDE.md
  Cargo.lock
  Cargo.toml
  PRPs/README.md
  PRPs/universal-text-document-identifier.STARTER.md
  PRPs/universal-text-document-identifier.md
  README.md
  docs/instructions.md
  src/neovim/client.rs
  src/neovim/integration_tests.rs
  src/neovim/mod.rs
  src/server/tools.rs
Labels: enhancement

#28 Add build-time metadata with Git information and timestamp
  Cargo.lock
  Cargo.toml
  build.rs
  flake.nix
  src/main.rs
Labels: enhancement

#38 Fix commit SHA detection for crates.io packages
  .github/workflows/CD.yaml
  .gitignore
  Cargo.toml
  build.rs
Labels: bug

#40 Fix Cargo.toml category format and CI publishing workflow
  .github/workflows/CD.yaml
  Cargo.toml
Labels: bug

#41 Add lsp_declaration tool for symbol declaration navigation
  CHANGELOG.md
  CLAUDE.md
  README.md
  docs/instructions.md
  flake.nix
  src/neovim/client.rs
  src/neovim/integration_tests.rs
  src/neovim/lua/lsp_declaration.lua
  src/neovim/testdata/cfg_lsp.lua
  src/server/tools.rs
Labels: enhancement

#43 Add lsp_formatting tool for document formatting with LSP
  CHANGELOG.md
  CLAUDE.md
  README.md
  docs/instructions.md
  src/neovim/client.rs
  src/neovim/integration_tests.rs
  src/neovim/lua/lsp_apply_text_edits.lua
  src/neovim/lua/lsp_formatting.lua
  src/neovim/mod.rs
  src/server/tools.rs
  src/test_utils.rs
Labels: enhancement

#45 Add lsp_range_formatting tool for document range formatting
  CHANGELOG.md
  CLAUDE.md
  README.md
  docs/instructions.md
  flake.nix
  src/neovim/client.rs
  src/neovim/integration_tests.rs
  src/neovim/lua/lsp_range_formatting.lua
  src/neovim/testdata/cfg_lsp.lua
  src/server/tools.rs
Labels: enhancement

#51 Release version 0.4.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: documentation

#52 Relax Diagnostic JSON schema
  src/neovim/client.rs
Labels: bug

#49 Add HybridToolRouter for Dynamic Tool Registration
  CHANGELOG.md
  CLAUDE.md
  README.md
  docs/instructions.md
  src/server/core.rs
  src/server/hybrid_router.rs
  src/server/mod.rs
  src/server/resources.rs
Labels: enhancement

#55 Add HTTP server transport support
  CHANGELOG.md
  CLAUDE.md
  Cargo.lock
  Cargo.toml
  README.md
  src/main.rs
Labels: enhancement

#60 Enhance LSP integration with configurable timeouts and improved test reliability
  CHANGELOG.md
  CLAUDE.md
  README.md
  docs/instructions.md
  src/neovim/client.rs
  src/neovim/integration_tests.rs
  src/neovim/lua/diagnostics_autocmd.lua
  src/neovim/lua/setup_autocmd.lua
  src/server/core.rs
  src/server/integration_tests.rs
  src/server/tools.rs
  src/test_utils.rs
Labels: enhancement

#75 Fix Lua tool discovery for empty tool registries
  CHANGELOG.md
  lua/nvim-mcp/init.lua
  src/server/integration_tests.rs
  src/server/lua_tools.rs
  src/test_utils.rs
Labels: bug

#77 Consolidate and improve project documentation
  CLAUDE.md
  PRPs/README.md
  PRPs/lua_dynamic_tools.STARTER.md
  PRPs/lua_dynamic_tools.md
  PRPs/mcp-server-implementation.STARTER.md
  PRPs/mcp-server-implementation.md
  PRPs/multi-connections.STARTER.md
  PRPs/multi-connections.md
  PRPs/nvim-api-integration.STARTER.md
  PRPs/nvim-api-integration.md
  PRPs/nvim-diagnostics-resources.STARTER.md
  PRPs/nvim-diagnostics-resources.md
  PRPs/universal-text-document-identifier.STARTER.md
  PRPs/universal-text-document-identifier.md
  README.md
  docs/development.md
  docs/resources.md
  docs/tools.md
  docs/usage.md
Labels: documentation

#80 Release v0.6.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
Labels: documentation

#82 Add dynamic connection status feature
  CHANGELOG.md
  src/main.rs
  src/neovim/client.rs
  src/neovim/integration_tests.rs
  src/server/core.rs
  src/server/integration_tests.rs
  src/server/resources.rs
  src/server/tools.rs
  src/test_utils.rs
Labels: enhancement

#84 Enhance cursor position tool with additional context information
  CHANGELOG.md
  src/server/integration_tests.rs
  src/server/lua/cursor_position.lua
  src/server/tools.rs
Labels: enhancement
